### ISSUE TITLE
Agent not starting

### ISSUE THREAD

**Issue by hmarr** [DataDog/heroku-buildpack-datadog#142]
It looks like we've had issues with the agent since Sept 23rd. Running `ps` in a heroku console shows the agent isn't running:

```
$ heroku run bash
Running bash on ⬢ <APP>... up, run.1453 (Standard-1X)
Starting Datadog Agent on <app>.run.1453
Starting Datadog Trace Agent on <app>.run.1453
~ $ 2019-11-05 09:48:42 UTC | CORE | INFO | (cmd/agent/app/start.go:124 in StartAgent) | Starting Datadog Agent v6.14.0
2019-11-05 09:48:42 UTC | CORE | INFO | (cmd/agent/app/start.go:152 in StartAgent) | Hostname is: <app>.run.1453
2019-11-05 09:48:42 UTC | CORE | INFO | (pkg/api/security/security.go:135 in FetchAuthToken) | Saved a new authentication token to /app/.apt/etc/datadog-agent/auth_token
2019-11-05 09:48:42 UTC | TRACE | INFO | (pkg/util/log/log.go:482 in func1) | Loaded configuration: /app/.apt/etc/datadog-agent/datadog.yaml
2019-11-05 09:48:42 UTC | TRACE | INFO | (pkg/trace/agent/run.go:109 in Run) | Trace agent running on host <app>.run.1453
2019-11-05 09:48:42 UTC | TRACE | INFO | (pkg/trace/api/api.go:151 in Start) | Listening for traces at http://localhost:8126
2019-11-05 09:48:42 UTC | CORE | INFO | (cmd/agent/app/start.go:179 in StartAgent) | GUI server port -1 specified: not starting the GUI.
2019-11-05 09:48:42 UTC | CORE | INFO | (pkg/forwarder/forwarder.go:155 in Start) | Forwarder started, sending to 1 endpoint(s) with 1 worker(s) each: "https://6-14-0-app.agent.datadoghq.com" (1 api key(s))
2019-11-05 09:48:42 UTC | CORE | INFO | (cmd/agent/app/start.go:219 in StartAgent) | logs-agent disabled
2019-11-05 09:48:42 UTC | CORE | INFO | (pkg/dogstatsd/listeners/udp.go:79 in Listen) | dogstatsd-udp: starting to listen on 127.0.0.1:8125
2019-11-05 09:48:42 UTC | CORE | INFO | (pkg/collector/runner/runner.go:92 in NewRunner) | Runner started with 4 workers.
2019-11-05 09:48:42 UTC | CORE | INFO | (pkg/collector/python/init.go:274 in Initialize) | Initializing rtloader with python2 /opt/datadog-agent/embedded
ImportError: No module named site
2019-11-05 09:48:52 UTC | TRACE | INFO | (pkg/trace/info/stats.go:101 in LogStats) | No data received

~ $ ps
  PID TTY          TIME CMD
    4 ?        00:00:00 bash
   60 ?        00:00:00 trace-agent
   95 ?        00:00:00 ps

~ $ agent-wrapper status
Getting the status from the agent.

Could not reach agent: Get https://localhost:5001/agent/status: dial tcp 127.0.0.1:5001: connect: connection refused
Make sure the agent is running before requesting the status and contact support if you continue having issues.
Error: Get https://localhost:5001/agent/status: dial tcp 127.0.0.1:5001: connect: connection refused
```

When trying to boot the agent manually, I get similar results:

```
~ $ agent-wrapper run
2019-11-05 09:45:29 UTC | CORE | INFO | (cmd/agent/app/start.go:124 in StartAgent) | Starting Datadog Agent v6.14.0
2019-11-05 09:45:29 UTC | CORE | INFO | (cmd/agent/app/start.go:152 in StartAgent) | Hostname is: <app>.run.5106
2019-11-05 09:45:30 UTC | CORE | INFO | (cmd/agent/app/start.go:179 in StartAgent) | GUI server port -1 specified: not starting the GUI.
2019-11-05 09:45:30 UTC | CORE | INFO | (pkg/forwarder/forwarder.go:155 in Start) | Forwarder started, sending to 1 endpoint(s) with 1 worker(s) each: "https://6-14-0-app.agent.datadoghq.com" (1 api key(s))
2019-11-05 09:45:30 UTC | CORE | INFO | (pkg/dogstatsd/listeners/udp.go:79 in Listen) | dogstatsd-udp: starting to listen on 127.0.0.1:8125
2019-11-05 09:45:30 UTC | CORE | INFO | (cmd/agent/app/start.go:219 in StartAgent) | logs-agent disabled
2019-11-05 09:45:30 UTC | CORE | INFO | (pkg/collector/runner/runner.go:92 in NewRunner) | Runner started with 4 workers.
2019-11-05 09:45:30 UTC | CORE | INFO | (pkg/collector/python/init.go:274 in Initialize) | Initializing rtloader with python2 /opt/datadog-agent/embedded
ImportError: No module named site
```

I tried pinning to an old agent version using `DD_AGENT_VERSION=6.11.3-1`, but the latest version still seems to get installed - see the following build logs:

```
-----> Installing datadog-agent_1%3a6.11.3-1_amd64.deb
-----> Installing datadog-agent_1%3a6.13.0-1_amd64.deb
-----> Installing datadog-agent_1%3a6.14.0-1_amd64.deb
```

And running the agent in a heroku console shows it's picking up the latest version:

```
~ $ agent-wrapper version
Agent 6.14.0 - Commit: 748545e - Serialization version: 4.12.0 - Go version: go1.12.9
```

Setting the `DD_PYTHON_VERSION=3` also didn't work:

```
Fatal Python error: initfsencoding: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f8beaffe700 (most recent call first):
SIGABRT: abort
PC=0x7f8bf6e2fe97 m=7 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f8bf6e2fe97
stack: frame={sp:0x7f8beaffd920, fp:0x0} stack=[0x7f8be9ffe268,0x7f8beaffde68)
00007f8beaffd820:  00007f8be0fe10b0  0000000000000001
...
```

**Comment by arapulido** [comment]
Hello @hmarr I will be looking at this right away. 

Some questions: what version of the Datadog Heroku Buildpack are you running? Also, what Heroku stack are you using? Heroku 16 or Heroku 18?

Thanks!

**Comment by hmarr** [comment]
Thanks! We're on `heroku-18` and the latest version of the buildpack (1.10).

**Comment by arapulido** [comment]
Thanks for your reply. OK, so I am guessing your issues started Oct 23rd, not Sep 23rd? Also, did you rebuild your slug with 1.10, then?

**Comment by arapulido** [comment]
@hmarr Also, while we are investigating the issue, rebuilding your slug with the buildpack version 1.9 (https://github.com/DataDog/heroku-buildpack-datadog/releases/tag/1.9) might workaround it.

**Comment by hmarr** [comment]
From our datadog charts, it looks like it was Sept 23rd so it coincided with the release of 1.8, not 1.10

**Comment by hmarr** [comment]
And it looks like we did rebuild with the new buildpacks right after release

**Comment by hmarr** [comment]
In case it helps, we’re also using the following buildpacks:
- ruby
- ruby-jemalloc
- heroku/metrics
- apt

**Comment by arapulido** [comment]
@hmarr thanks! there has been a bit of changes that can be related between 1.8 and 1.10. To avoid looking at two different issues at the same time, let's do the following:

* For the current version, as the `trace-agent` is running correctly, would you mind telling us the output of `cat /prod/<pid of the trace-agent>/environ` please? so we know what environment is using the `agent` to run (they use the same one)

* Also, would you mind rebuilding with `1.8` and see what errors you get there? I doubt it would be the same ones.

**Comment by arapulido** [comment]
@hmarr seeing that you have 3 different versions of the agent, it seems that you are getting conflicts with the cache. Can you try cleaning up your build cache (https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache) and rebuild your slug (it can be with `1.10`). I think that might solve the issue

**Comment by hmarr** [comment]
Just tried clearing the build cache and that does seem to have fixed it! 🎉 

Thanks so much for your help getting to the bottom of this. 🙌 🙌 🙌

**Comment by arapulido** [comment]
@hmarr Cool! Good to know. We will think about this to try to avoid this from happening in the future and/or document better.

**Comment by hmarr** [comment]
@arapulido I just noticed that we were still pinning to v6.11.3-1 of the agent. I removed that to move us to the latest version, purged the cache, and things went back to the bad state we were in previously:

```
~ $ agent-wrapper run
2019-11-05 14:19:48 UTC | CORE | INFO | (cmd/agent/app/start.go:124 in StartAgent) | Starting Datadog Agent v6.14.0
2019-11-05 14:19:48 UTC | CORE | INFO | (cmd/agent/app/start.go:152 in StartAgent) | Hostname is: 3dc5c577-2ec8-4eaf-ae20-7cef16b2415f
2019-11-05 14:19:50 UTC | CORE | INFO | (cmd/agent/app/start.go:179 in StartAgent) | GUI server port -1 specified: not starting the GUI.
2019-11-05 14:19:50 UTC | CORE | INFO | (pkg/config/config.go:827 in getMultipleEndpointsWithConfig) | No API key provided for domain "https://app.datadoghq.com", removing domain from endpoints
2019-11-05 14:19:50 UTC | CORE | INFO | (pkg/forwarder/forwarder.go:155 in Start) | Forwarder started, sending to 0 endpoint(s) with 1 worker(s) each:
2019-11-05 14:19:50 UTC | CORE | ERROR | (pkg/forwarder/forwarder_health.go:91 in healthCheckLoop) | No valid api key found, reporting the forwarder as unhealthy.
2019-11-05 14:19:50 UTC | CORE | INFO | (cmd/agent/app/start.go:219 in StartAgent) | logs-agent disabled
2019-11-05 14:19:50 UTC | CORE | INFO | (pkg/dogstatsd/listeners/udp.go:79 in Listen) | dogstatsd-udp: starting to listen on 127.0.0.1:8125
2019-11-05 14:19:50 UTC | CORE | INFO | (pkg/collector/runner/runner.go:92 in NewRunner) | Runner started with 4 workers.
2019-11-05 14:19:50 UTC | CORE | INFO | (pkg/collector/python/init.go:274 in Initialize) | Initializing rtloader with python2 /opt/datadog-agent/embedded
ImportError: No module named site
```

I've re-pinned us to v6.11.3-1 and we're getting metrics again, so it does seem like there's still an issue with the latest version.

**Comment by arapulido** [comment]
Thanks for reporting again and reopening. 

So, back to my previous comment:

For the current version, as the `trace-agent` is running correctly, would you mind telling us the output of cat /prod/<pid of the trace-agent>/environ please? so we know what environment is using the agent to run (they use the same one). Thanks!

**Comment by hmarr** [comment]
Ah, I think I've spotted the problem - the `PYTHONPATH` has become garbled (related to installing multiple versions?)

```
PYTHONPATH=/app/.apt/opt/datadog-agent/embedded/lib:/app/.apt/opt/datadog-agent/bin/agent/dist:/app/.apt/opt/datadog-agent/embedded/lib/python2.7python3.7/lib-dynload:/app/.apt/opt/datadog-agent/embedded/lib/python2.7python3.7/lib-tk:/app/.apt/opt/datadog-agent/embedded/lib/python2.7python3.7/plat-linux2:/app/.apt/opt/datadog-agent/embedded/lib/python2.7python3.7:/app/.apt/opt/datadog-agent/embedded/lib/python2.7python3.7/site-packages
```

Here's a more complete (but redacted) version of `/proc/<pid>/environ` for the trace agent:

```
LD_LIBRARY_PATH=/app/.apt/opt/datadog-agent/embedded/lib:/app/.apt/usr/lib/x86_64-linux-gnu:/app/.apt/usr/lib
PYTHONPATH=/app/.apt/opt/datadog-agent/embedded/lib:/app/.apt/opt/datadog-agent/bin/agent/dist:/app/.apt/opt/datadog-agent/embedded/lib/python2.7python3.7/lib-dynload:/app/.apt/opt/datadog-agent/embedded/lib/python2.7python3.7/lib-tk:/app/.apt/opt/datadog-agent/embedded/lib/python2.7python3.7/plat-linux2:/app/.apt/opt/datadog-agent/embedded/lib/python2.7python3.7:/app/.apt/opt/datadog-agent/embedded/lib/python2.7python3.7/site-packages
_=/app/.apt/opt/datadog-agent/embedded/bin/trace-agent
LANG=en_US.UTF-8
DOGSTATSD_HOST=127.0.0.1
DD_LOG_FILE=/app/.apt/var/log/datadog/datadog.log
DD_API_KEY=<REDACTED>
DD_DISABLE_HOST_METRICS=true
DYNO=web.1
DD_DYNO_HOST=true
DD_BIN_DIR=/app/.apt/opt/datadog-agent/bin/agent
PWD=/app
HOME=/app
CPATH=/app/.apt/usr/include:/app/.apt/usr/include/x86_64-linux-gnu:
DD_LD_LIBRARY_PATH=/app/.apt/opt/datadog-agent/embedded/lib:/app/.apt/usr/lib/x86_64-linux-gnu:/app/.apt/usr/lib
LIBRARY_PATH=/app/.apt/usr/lib/x86_64-linux-gnu:/app/.apt/usr/lib/i386-linux-gnu:/app/.apt/usr/lib:
DOGSTATSD_PORT=8125
SHLVL=2
CPPPATH=/app/.apt/usr/include:/app/.apt/usr/include/x86_64-linux-gnu:
PATH=/app/.apt/usr/bin:/app/.apt/opt/datadog-agent/bin/agent:/app/.apt/usr/bin:/usr/local/bin:/usr/bin:/bin
DATADOG_CONF=/app/.apt/etc/datadog-agent/datadog.yaml
PKG_CONFIG_PATH=/app/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:/app/.apt/usr/lib/i386-linux-gnu/pkgconfig:/app/.apt/usr/lib/pkgconfig:
DD_PYTHONPATH=/app/.apt/opt/datadog-agent/embedded/lib:/app/.apt/opt/datadog-agent/bin/agent/dist:/app/.apt/opt/datadog-agent/embedded/lib/python2.7python3.7/lib-dynload:/app/.apt/opt/datadog-agent/embedded/lib/python2.7python3.7/lib-tk:/app/.apt/opt/datadog-agent/embedded/lib/python2.7python3.7/plat-linux2:/app/.apt/opt/datadog-agent/embedded/lib/python2.7python3.7:/app/.apt/opt/datadog-agent/embedded/lib/python2.7python3.7/site-packages
INCLUDE_PATH=/app/.apt/usr/include:/app/.apt/usr/include/x86_64-linux-gnu:
DD_HOSTNAME=<app>.web.1
```

**Comment by hmarr** [comment]
It looks like this is the offending line of code:

https://github.com/DataDog/heroku-buildpack-datadog/blob/e1b553c840eb3204481166f5c399d3dd2a132684/extra/datadog.sh#L107

Run on one of our dynos it returns `python2.7python3.7`

**Comment by arapulido** [comment]
> It looks like this is the offending line of code:
> 
> https://github.com/DataDog/heroku-buildpack-datadog/blob/e1b553c840eb3204481166f5c399d3dd2a132684/extra/datadog.sh#L107
> 
> Run on one of our dynos it returns `python2.7python3.7`

This is very interesting, @hmarr, thanks a lot for helping us debugging this issue. 

During compilation of the slug, it should remove one version or the other of python, and I am wondering why it is not doing it for you.

I think that the problem (and something we should document better) is that if you select `DD_AGENT_VERSION`, you should clear the cache and recompile the slug. The version is selected during compilation time, and most of the logic depends on that.

Actually, `PYTHONPATH` is not exported anymore in `1.10`, so the fact that it is being exported for you, means that you are still using the previous one.

Can you try doing the following: change `DD_AGENT_VERSION` to `6.14.0-1` for your Heroku applications, clear build cache, rebuild your slug, and see if it works?

Thanks!

**Comment by arapulido** [comment]
@hmarr Hello! Any chance to try what I mentioned in the comment above, please? Thanks!

**Comment by hwong** [comment]
We ran into a same issue and clearing the build cache and rebuilding the Heroku slug solved the problem.

**Comment by arapulido** [comment]
@hmarr Hello again! I was finally able to reproduce your issue and I think that I might know what's going on. 

If the Datadog buildpack is above the apt one, the apt one reinstalls the deb agent: https://github.com/heroku/heroku-buildpack-apt/blob/master/bin/compile#L96

Reinstalling the deb agent as it is, without our post processing, leaves the agent with 2 different embedded python version, hence the error in your DD_PYTHONPATH

To fix the issue:
```
heroku buildpacks:remove https://github.com/DataDog/heroku-buildpack-datadog
heroku buildpacks:add https://github.com/DataDog/heroku-buildpack-datadog
```
(basically removing our buildpack and adding it again, so it comes after the apt one).

Then set `DD_AGENT_VERSION` back to `6.14.0-1`, clear your build cache, and rebuild your slug.

Let me know if you are able to try that and whether it fixes the issue for you. Thanks for your patience!

**Comment by arapulido** [comment]
@hmarr hello again! Did you get any chance to try my suggestion above? ☝️ Thanks!

**Comment by arapulido** [comment]
@hmarr hey! I believe that your issue is what I described in https://github.com/DataDog/heroku-buildpack-datadog/issues/142#issuecomment-555933970

I will close this issue now, but feel free to reopen it if you still have the issue after having applied my suggestion there. 

Thanks!

**Comment by hmarr** [comment]
@arapulido hi there! Thanks for continuing to dig into this and sorry for the radio silence - I never found time to pick this up again after I put it on hold due to some vacation.

I've just tested out your suggestion and it seems to work perfect - reordering the buildpacks did the trick 🎉 

Thanks again for all your help with this 🙌

**Comment by arapulido** [comment]
@hmarr Thanks for following this up and very glad to hear it solved your issue!
